### ISSUE TITLE
Broken Whitelist Crashing

### ISSUE THREAD

**Issue by Nebulous01** [rwilliaise/schmucks#3] opened 2021-06-12 01:14 UTC
**Description**
When players on my server try to whitelist a block with the schmucks mod, their game begins to repeatedly crash when trying to join. The only way we have been able to fix is by removing and re adding the mod in completely.

**To Reproduce**
1. Go to minecraft
2. whitelist something with the schmuck staff
3. Game crashes

**Expected behavior**
Blocks are supposed to be whitelisted for use

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Java Version: build 16.0.1+9
 - Version: 1.3.2
 - Minecraft Version: 1.17 (latest)
 - Sodium installed: yes
 
 - Other mods: 
 artisanat-2.1.jar
 bagels_baking-1.17+-+0.3.4.jar 
 bigbeacons-1.2.0.jar
 biome_locator-1.17-1.1.2.jar 
 blockus-2.2.0+1.17-rc1.jar 
companion-bats-fabric-1.16.3.jar
Croptopia-1.17-rc2-FABRIC-1.4.1.jar
crusade-mod-1.2.4.jar
DarkPaintings-fabric-1.17-3.0.6.jar
dawn-2.0.2.jar
Earth2Java-1.7.1+1.17.jar
elementalcreepers-1.4.0.jar
endermen-are-friends-1.1-mc1.17-fabric.jar
fabric-api-0.34.9+1.17.jar
Fabric-Discord-Link-0.9.4.ja
fabric-language-kotlin-1.6.1+kotlin.1.5.10.ja
FabricHomes-2.0.0.jar
FabricTPA-3.0.1.jar
FabricWarps-2.0.0.jar
fallingleaves-1.7.0+1.17.jar
fast-chest-1.2+1.17.jar
FatExperienceOrbs-1.0.0.jar
flytre_lib-1.17-0.2.13.jar
GiveMeHats-1.6.jar
golfiv-0.3.2.jar
inmis-2.3.0-1.17-rc2.jar
InvView-1.4.2-1.17+.jar
lambdynamiclights-2.0.0+1.17.jar
lithium-fabric-mc1.17-rc1-0.7.0-SNAPSHOT.jar
mighty_mangoes-1.0.4.jar
NewCaves.jar
pipe-1.17-1.3.1.jar
plantinajar-2.2.1.jar
promenade-2.1.1.jar
quicksand-1.0.2+fabric-mc1.17.jar
rightclickharvest-1.2.4.jar
RingsOfAscension-1.17-1.0.jar
simple-cobblestone-generator-1.1.2.jar
starlight-fabric-1.0.0-RC2-21w20a.jar 
TacoCraft-1.6.1+mc.1.17.jar 
 terrarian-slimes-1.0.3-BETA+1.17.jar
trinkets-3.0.0.jar
universal_ores-1.0.jar
unsaddleeeee-1.0+mc1.17-Fabric.jar
voicechat-1.17-1.0.2.jar

**Additional context** 
This is very inconvenient for many players on my server

**Comment by rwilliaise** [comment] 2021-06-12 05:43
Could one of your players provide a log? Also could you provide a log from the server? Thank you for reporting!

**Comment by rwilliaise** [comment] 2021-06-16 17:06
I'm going to close this tomorrow or the day after, as no log has been given. Sorry! I would guess that this is an incompatibility with Sodium, but I cannot reproduce this.

**Closed as completed** 2021-06-28 06:39 UTC
Labels: bug, critical
